[theme]
# Gold buttons to pop against the white and green
primaryColor="#fcba06" 

backgroundColor="#FFFFFF"

# Solid Dark Green Sidebar
secondaryBackgroundColor="#03542b" 

# Dark text for the MAIN page
textColor="#262730"
