[theme]
# The main accent color (used for the 'Calculate Route' button, loading bars, etc.)
primaryColor="#03542b"

# The main background color of the website
backgroundColor="#dedede"

# The background color of the sidebar
secondaryBackgroundColor="#f7c812"

# The color of the text
textColor="FFFFFF"

# Font style ("sans serif", "serif", or "monospace")
font="sans serif"
